<a href="https://colab.research.google.com/github/njwbilll/Tugas-3_Practical-Linear-Algebra-O-Reilly-_Najwa-Bilqis-Al-Khalidah/blob/main/08_Matrix_Inverse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 8: Matrix Inverse

**Referensi:** Practical Linear Algebra for Data Science (Mike X Cohen)

***

## Ringkasan Materi
Invers matriks adalah analogi aljabar dari pembagian. Matriks A dikalikan dengan inversnya (A^-1) akan menghasilkan matriks identitas. Bab ini membahas syarat invertibilitas, metode komputasi, serta konsep Moore-Penrose Pseudoinverse untuk matriks yang tidak memiliki invers sempurna.

### Topik yang Dibahas:
1. Konsep Invertibilitas & Matriks Singular
2. Invers Matriks 2x2 & Diagonal
3. Moore-Penrose Pseudoinverse
4. Stabilitas Numerik & Interpretasi Geometris


In [1]:
import numpy as np

# 1. Invers Matriks 2x2
A = np.array([[1, 2], [3, 4]])
A_inv = np.linalg.inv(A)
print("Matriks A:\n", A)
print("Invers A:\n", A_inv)
print("Verifikasi (A @ A_inv = I):\n", np.round(A @ A_inv))

# 2. Invers Matriks Diagonal
D = np.diag([2, 5, 10])
D_inv = np.diag(1 / np.diag(D))
print("\nInvers Matriks Diagonal:\n", D_inv)


Matriks A:
 [[1 2]
 [3 4]]
Invers A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Verifikasi (A @ A_inv = I):
 [[1. 0.]
 [0. 1.]]

Invers Matriks Diagonal:
 [[0.5 0.  0. ]
 [0.  0.2 0. ]
 [0.  0.  0.1]]


***
## Moore-Penrose Pseudoinverse

### Penjelasan Teori
Jika matriks tidak memiliki invers (misalnya karena matriks tersebut tidak persegi atau rank-nya tidak penuh/singular), kita menggunakan **Moore-Penrose Pseudoinverse**. Ini sangat berguna dalam *Least Squares* untuk mencari solusi aproksimasi terbaik.

In [2]:
# Matriks non-invertibel (singular)
S = np.array([[1, 2], [2, 4]])

# np.linalg.inv(S) akan error, gunakan pinv
S_pinv = np.linalg.pinv(S)
print("Pseudoinverse dari matriks singular:\n", S_pinv)


Pseudoinverse dari matriks singular:
 [[0.04 0.08]
 [0.08 0.16]]


***
## Interpretasi Geometris

Secara geometris, invers membalikkan transformasi ruang. Jika matriks A merentangkan sebuah objek, inversnya akan menyusutkan kembali objek tersebut ke bentuk aslinya.


