<a href="https://colab.research.google.com/github/njwbilll/Tugas-3_Practical-Linear-Algebra-O-Reilly-_Najwa-Bilqis-Al-Khalidah/blob/main/14_Singular_Value_Decomposition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 14: Singular Value Decomposition (SVD)

**Referensi:** Practical Linear Algebra for Data Science (Mike X Cohen)

***

## Ringkasan Materi
SVD adalah dekomposisi matriks yang dapat diterapkan pada semua jenis matriks, tidak terbatas pada matriks persegi. SVD memecah matriks $A$ menjadi $U \Sigma V^T$. Komponen ini mengungkapkan struktur informasi data, memungkinkan reduksi dimensi, dan memberikan solusi yang sangat stabil secara numerik untuk masalah pseudoinverse.

### Topik yang Dibahas:
1. Konsep U, Sigma, dan V^T
2. Hubungan SVD dengan Eigenvalues
3. Representasi matriks sebagai susunan layer (Rank-1 Layers)
4. Moore-Penrose Pseudoinverse via SVD


In [1]:
import numpy as np
from numpy import linalg as LA

# 1. SVD dalam Python
A = np.random.randn(5, 3)
U, S, VT = LA.svd(A, full_matrices=False)

print("Bentuk U:", U.shape)
print("Nilai Singular (S):", S)
print("Bentuk VT:", VT.shape)


Bentuk U: (5, 3)
Nilai Singular (S): [2.61096304 2.0355827  1.30541951]
Bentuk VT: (3, 3)


***
## Rank-1 Layers dan Kompresi

### Penjelasan Teori
Matriks $A$ dapat dipandang sebagai penjumlahan dari beberapa matriks berperingkat satu (rank-1 layers). Jika kita hanya mengambil beberapa komponen singular terbesar, kita melakukan kompresi data dengan tetap mempertahankan esensi informasi matriks tersebut.



In [2]:
# Konstruksi matriks A dari layer pertama
layer1 = S[0] * np.outer(U[:, 0], VT[0, :])

print("Layer pertama (Rank-1) dari matriks A:\n", layer1)


Layer pertama (Rank-1) dari matriks A:
 [[ 1.25733251 -0.83101037 -0.50435523]
 [ 1.21507503 -0.80308107 -0.48740443]
 [ 0.65392491 -0.43219941 -0.26230964]
 [ 0.56623766 -0.37424417 -0.22713556]
 [ 0.67912173 -0.44885278 -0.27241688]]


***
## Pseudoinverse via SVD

### Penjelasan Teori
Pseudoinverse Moore-Penrose dapat dihitung secara langsung dari komponen SVD. Jika $A = U \Sigma V^T$, maka $A^+ = V \Sigma^+ U^T$, di mana $\Sigma^+$ adalah kebalikan dari nilai singular yang tidak nol. Ini memberikan solusi yang jauh lebih stabil dibandingkan metode invers matriks standar untuk matriks yang mendekati singular atau tidak persegi.

In [3]:
# Menghitung Pseudoinverse menggunakan SVD
S_inv = np.diag(1/S)
A_pinv = VT.T @ S_inv @ U.T

print("Pseudoinverse dihitung via SVD:\n", A_pinv)
print("\nVerifikasi dengan np.linalg.pinv:\n", LA.pinv(A))


Pseudoinverse dihitung via SVD:
 [[ 0.10830886  0.05904721  0.08131584  0.26726994  0.31429668]
 [-0.02099408 -0.41454353  0.02518408 -0.12059601  0.24774386]
 [-0.43002803  0.12029426 -0.22085061  0.53415445 -0.02146765]]

Verifikasi dengan np.linalg.pinv:
 [[ 0.10830886  0.05904721  0.08131584  0.26726994  0.31429668]
 [-0.02099408 -0.41454353  0.02518408 -0.12059601  0.24774386]
 [-0.43002803  0.12029426 -0.22085061  0.53415445 -0.02146765]]
